### ISSUE TITLE
yaml file

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh.aws#4]
the yaml file needs to be changed to have

```
cloudmesh:
   clouds:
      aws:
           cm_label: ...
           other cm fileds ...
           credentials:
                  ...
           defaults:
               image: ...
               flavor: ...

```

only this way we can integrate with existing yaml files.
